resources:
  - name: concourse-saas
    type: git
    source:
      uri: https://github.com/jtarchie/concourse-sass
      branch: master

jobs:
  - name: tests
    plan:
      - get: concourse-saas
      - task: rspec
        file: concourse-saas/ci/tasks/rspec.yml
