---
platform: linux
image: /var/vcap/packages/git_resource

params:
  ENDPOINT:
  PASSWORD:
  PIPELINE:
  USERNAME:

inputs:
  - name: repo
  - name: concourse-saas

run:
  path: sh
  args:
    - -c
    - |
      set -ex
      curl "$ENDPOINT/api/v1/cli?arch=amd64&platform=linux" -o ./fly
      chmod +x ./fly
      ./fly -t endpoint login -c $ENDPOINT -k -u $USERNAME -p $PASSWORD
      ./fly -t endpoint set-pipeline     -n -p $PIPELINE -c repo/.concourse.yml
      ./fly -t endpoint unpause-pipeline -p $PIPELINE
